# Use new container infrastructure to enable caching
sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack.
matrix:
  include:
  - env: BUILD=cabal
    language: haskell
    ghc: 7.4
  - env: BUILD=cabal
    language: haskell
    ghc: 7.6
  - env: BUILD=cabal
    language: haskell
    ghc: 7.8
  - env: BUILD=stack RESOLVER=lts-3.22
    language: generic
    addons: { apt: { packages: [ libgmp-dev ] } }
  - env: BUILD=stack RESOLVER=lts-6.30
    language: generic
    addons: { apt: { packages: [ libgmp-dev ] } }
  - env: BUILD=stack RESOLVER=lts-7.19
    language: generic
    addons: { apt: { packages: [ libgmp-dev ] } }
  - env: BUILD=stack RESOLVER=lts-8.3
    language: generic
    addons: { apt: { packages: [ libgmp-dev ] } }
  - env: BUILD=stack RESOLVER=lts-8.3
    os: osx
    language: generic
  - env: BUILD=stack RESOLVER=nightly
    language: generic
    addons: { apt: { packages: [ libgmp-dev ] } }


  allow_failures:
  - env: BUILD=stack RESOLVER=nightly
    language: generic
    addons: { apt: { packages: [ libgmp-dev ] } }
  - env: BUILD=cabal
    language: haskell
    ghc: 7.4

install:
  - export PATH=$HOME/.local/bin::$HOME/.cabal/bin:$PATH
  - mkdir -p ~/.local/bin
  - |
    case "$BUILD" in
      stack)
        if [ `uname` = "Darwin" ]
        then
          travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
        else
          travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        fi
      ;;
    cabal)
      ;;
    esac

script:
- |
  set -ex
  if [ "x${RUNTEST}" = "xfalse" ]; then exit 0; fi
  case "$BUILD" in
    stack)
      rm stack.yaml && ln -sv .travis/stack-${RESOLVER}.yaml stack.yaml
      stack --no-terminal test --flag foundation:bounds-check --install-ghc --coverage --bench --no-run-benchmarks --haddock --no-haddock-deps
      ;;
    cabal)
      cabal install --only-dependencies --enable-tests --enable-benchmarks
      cabal test
      cabal check
      cabal sdist
      ;;
  esac
  set +ex
